-- START OF SCRIPT

DROP DATABASE IF EXISTS NETFLIX_BCK;

CREATE DATABASE NETFLIX_BCK;

USE NETFLIX_BCK;

CREATE USER IF NOT EXISTS 'net4flix'@'localhost' IDENTIFIED BY 'NETFLIX_BCK_PWD';

GRANT ALL PRIVILEGES ON NETFLIX_BCK.* TO 'net4flix'@'localhost' WITH GRANT OPTION;

FLUSH PRIVILEGES;

-- END OF SCRIPT